# Generated by Django 2.2.5 on 2020-01-07 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0002_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='content',
            field=models.CharField(default='', max_length=20, verbose_name='消息内容'),
        ),
    ]
