# Generated by Django 2.2.5 on 2020-01-07 14:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0003_message_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='belong_to_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='所属用户', to='trade.User', verbose_name='商品拥有者'),
        ),
    ]
